version: 0.0
os: linux
files:
  - source: /danny-s-photography-site/
    destination: /var/www/html
hooks:
  BeforeInstall:
   - location: /Photosnap-master/
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
